# Data

```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/setup.R"))
```
First, the details of the data will be shown in here after doing the data cleaning. 
```{r}
data <- read.csv(here::here("data/GermanCredit.csv"), sep=";", header=T)

# replace description of categorical variables, make it visible

# data$CHK_ACCT[which(data$CHK_ACCT=='0')] <- "less than 0DM"
# data$CHK_ACCT[which(data$CHK_ACCT=='1')] <- "0 to 200DM"
# data$CHK_ACCT[which(data$CHK_ACCT=='2')] <- "more than 200DM"
# data$CHK_ACCT[which(data$CHK_ACCT=='3')] <- "no checking account"
# 
# data$HISTORY[which(data$HISTORY=='0')] <- "no credit taken"
# data$HISTORY[which(data$HISTORY=='1')] <- "this bank credits paid duly"
# data$HISTORY[which(data$HISTORY=='2')] <- "existing credits paid duly"
# data$HISTORY[which(data$HISTORY=='3')] <- "paid delay in past"
# data$HISTORY[which(data$HISTORY=='4')] <- "critical account"
# 
# data$SAV_ACCT[which(data$SAV_ACCT=='0')] <- "less than 100DM"
# data$SAV_ACCT[which(data$SAV_ACCT=='1')] <- "100 to 500DM"
# data$SAV_ACCT[which(data$SAV_ACCT=='2')] <- "500 to 1000DM"
# data$SAV_ACCT[which(data$SAV_ACCT=='3')] <- "more than 1000DM"
# data$SAV_ACCT[which(data$SAV_ACCT=='3')] <- "unknown/no saving account"
# 
# data$EMPLOYMENT[which(data$EMPLOYMENT=='0')] <- "unemployed"
# data$EMPLOYMENT[which(data$EMPLOYMENT=='1')] <- "less than 1 year"
# data$EMPLOYMENT[which(data$EMPLOYMENT=='2')] <- "1 to 4 years"
# data$EMPLOYMENT[which(data$EMPLOYMENT=='3')] <- "4 to 7 years"
# data$EMPLOYMENT[which(data$EMPLOYMENT=='4')] <- "more than 7 years"

data.bcol <- data %>% select(2,4:10,12,13,15:26,28,30,31) %>% colnames()
for(i in data.bcol){
    data[,i] <- as.factor(data[,i])
}

```

```{r}
data %>% datatable(option = list(scrollX = T))
```

*not sure if it need to replace the binary values, it may be hard to read in chart otherwise.   

## Structure of data
```{r}
str(data)
```

```{r}
summary(data)
```

There are no missing value.
```{r}
sum(is.na(data))
```