# 3 Data preparation for models

```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/setup.R"))
```

## 3.1 Train set and test set

```{r}
set.seed(123)
index.tr <- createDataPartition(y=Credit$RESPONSE,p=0.8,list=FALSE)
Credit.tr <- Credit[index.tr,]
Credit.te <- Credit[-index.tr,]
```


```{r}
table(Credit.tr$RESPONSE)
```

# 4. supervised learning 

## 4.1 classification tree
```{r}
credit.tree <- caret::train(RESPONSE ~ .,
                           data = Credit.tr,
                           method ="rpart",
                           preProcess = NULL,
                           trControl=trainControl(method="repeatedcv", number=10,
                                                  repeats=10, verboseIter=FALSE,
                                                  sampling="up"))

rpart.plot(credit.tree$finalModel)
credit.tree
```


```{r}
Credit.pred <- predict(credit.tree,newdata=Credit.te)
confusionMatrix(data=Credit.pred, reference = Credit.te$RESPONSE)
# draw a confusion matrix plot later
```

##4.2 logistic regression
```{r}

```


# 5. unsupervised learing
## 5.1 Clustering  

```{r}
credit.d <- dist(Credit.copy[,-32], method = "manhattan")

# credit.d.melt <- melt(as.matrix(credit.d)) 
# head(credit.d.melt)
# 
# ggplot(data = credit.d.melt, aes(x=Var1, y=Var2, fill=value)) + 
#   geom_tile()

credit.hc <- hclust(credit.d, method = "complete")
plot(credit.hc, hang=-1)

plot(credit.hc, hang=-1)
rect.hclust(credit.hc, k=6)
# credit.clust <- cutree(credit.hc, k=6)
# credit.clust
```

```{r}
# Choice of the number of clusters
# fviz_nbclust(data[,-32],
#              hcut, hc_method="complete",
#              hc_metric="manhattan",
#              method = "wss", 
#              k.max = 25, verbose = FALSE)
# fviz_nbclust(data[,-32],
#              hcut, hc_method="complete",
#              hc_metric="manhattan",
#              method = "silhouette", 
#              k.max = 25, verbose = FALSE)
# fviz_nbclust(data[,-32],
#              hcut, hc_method="complete",
#              hc_metric="manhattan",
#              method = "gap", 
#              k.max = 25, verbose = FALSE)
```

```{r}
#K-means
# 
# fviz_nbclust(data[,-32],
#              kmeans,
#              method = "wss", 
#              k.max = 25, verbose = FALSE)
# fviz_nbclust(data[,-32],
#              kmeans, 
#              method = "silhouette", 
#              k.max = 25, verbose = FALSE)
# fviz_nbclust(data[,-32],
#              kmeans,
#              method = "gap", 
#              k.max = 25, verbose = FALSE)

# credit.km <- kmeans(data[,-32], centers=2)
# credit.km$cluster

#PAM method

```
